pipeline {
    agent any
    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/namanpachauli/microservice-monitor.git'
            }
        }
        stage('Docker Build (Manual)') {
            steps {
                echo "Docker build stage manually host pe run karo:"
                echo "docker build -t monitor-image:latest -f monitor.Dockerfile ."
            }
        }
        stage('Deploy (Optional)') {
            steps {
                echo "Kubernetes deploy optional. Run:"
                echo "kubectl apply -f k8s/"
            }
        }
    }
}